### ISSUE TITLE
Running behind reverse proxy with path rewrite

### ISSUE THREAD

**Issue by joshmue** [Flagsmith/flagsmith-frontend#38]
I tried to run the frontend behind a reverse proxy with some URL prefix.
Routes being served kind of like this:

- `/flagsmith/ui/` to the flagsmith frontend address
- `/flagsmith/api/` to the flagsmith api address
- `/something/else/` to somewhere else

The prefix is always trimmed in the request to the actual backend.

Unfortunately, this causes problems for the frontend. For example, in the page HTML, there are references to images starting with `/images/...` which tells the browser to query `/images/...` instead of `/flagsmith/ui/images`, which fails.

I could not find instructions to set a certain base url or base path to use, like some projects do.
Is there anything that I missed? Maybe serving flagsmith on its own domain a better idea either way?

**Comment by dabeeeenster** [comment]
Hi,

The platform is designed to be run with each service having its own domain name - we don't currently support running the applications in subdirectories like that I'm afraid.
