### ISSUE TITLE
Support for serving in subdirectory/path

### ISSUE THREAD

**Issue by emiliorcueto** [Flagsmith/flagsmith-frontend#39]
Currently, we are implementing flagsmith behind a gateway in a k8s cluster.  For the frontend specifically, we have set the ASSET_URL to the appropriate path.  E.g. `http://localhost:4200/flags-admin/` 

In the webpack config, using url.resolve(), this ultimately translates to `http://localhost:4200/flags-admin/static/`

However, there are several issues when doing this.  For example, the app attempts to load images and fonts at `/images/` and `/fonts/`.  This is easily resolved by adding matching routes to the gateway proxy. 

The main issue is that the app is rewriting the browser history, under the assumption that it lives at the root of the domain, and typical user behavior causes it to fail (such as refreshing a page, etc).  Additionally, accessing the primary login screen is also a challenge.  The app will not render the login screen despite all requests coming back 200.  You can "trick" the app to render the screen by setting `t` cookie with a bad value, or by navigating to any of the paths defined [here](https://github.com/Flagsmith/flagsmith-frontend/blob/491bd1b81a99a167d07d9ad8e21b47b81b7a8512/web/main.js#L76).  This will force the app to render the screen and add a `redirect` query param.  This however does not resolve the usability issue as the app could easily fail should a user manually refresh or click a bookmarked link, etc.

It would make the most sense to refactor the routing system to respect the ASSET_URL across the codebase.  This would 
 then allow support for "/" as easily as "/custom-path".

**Comment by dabeeeenster** [comment]
Happy to take a Pull Request on this issue! For us we run the app from its own domain but if someone else wants to pick this up that would be great and would get a merge into master.

**Comment by jordykirkman** [comment]
@dabeeeenster Just created a PR! Let me know if something like this works.

**Comment by KOGI** [comment]
@dabeeeenster just FYI, #41 has now been merged, so this ticket can be closed at your convenience :)
