### ISSUE TITLE
Feature Request : Add categories for features

### ISSUE THREAD

**Issue by JFCote** [Flagsmith/flagsmith-frontend#4]
We currently get around this missing feature by defining convention like:

* show_new_grid_a
* show_new_grid_b
* show_new_grid_c

Would be nice to put them all in a category for quick visualization

* New_grid_transition
    * show_new_grid_a
    * show_new_grid_b
    * show_new_grid_c

But it would be nice to be able to create category to quickly see without doing a search.

I don't think category should be something related to the API, it should only be used for classification help.

**Comment by kyle-ssg** [comment]
Added this to our Trello, I think tagging features and filtering by one or more tags would be useful to those with quite a big projects.

**Comment by JFCote** [comment]
@kyle-ssg Is this a public Trello?

**Comment by dabeeeenster** [comment]
Hi @JFCote its not public yet but we are working on a public board. This feature is actually almost done and will be deployed to production soon.

**Comment by kyle-ssg** [comment]
Hi @JFCote, just to let you know, our public roadmap can now be found [here](https://product-hub.io/roadmap/5d81f2406180537538d99f28).

**Comment by JFCote** [comment]
@kyle-ssg Thanks for the info!

**Comment by kyle-ssg** [comment]
No problem @JFCote, also just to let you know feature tags this is the current WIP feature I'm looking at.

<img src="http://g.recordit.co/JseUeOH3it.gif"/>

**Comment by kyle-ssg** [comment]
This is the longest an issue has been open, apologies! Incase you haven't seen, feature tagging has been in production a few weeks now.

**Comment by JFCote** [comment]
Oh nice! Will definitely try it out! Thanks

**Comment by kyle-ssg** [comment]
No problem at all! I think we will end up adding some sort of "What's new" section in the frontend as we roll out stuff.

**Comment by JFCote** [comment]
Hey @kyle-ssg , just tested this out and it works great. Only one thing that would be nice is to be able to filter by these tags. Its very nice to see the color and it helps a lot but it would be nice to be able on top of the feature list to enter tags and it filters automatically the list underneath.

Do you think that would be possible?
Thanks!

**Comment by kyle-ssg** [comment]
@JFCote yep totally right. This is now live :).

**Comment by JFCote** [comment]
@kyle-ssg Oh nice, that was quick!!!
